moods/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MoodView.as_view(), name='moods'),
]

suhail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moods.urls'))
]

moods/models.py
from django.db import models

class Mood(models.Model):
	MOODSWING_CHOICES = [
        (-2, 'Very Hard'),
        (-1, 'Hard'),
        (0, 'Normal'),
        (1, 'Good'),
        (2, 'Very Good'),
    ]
	moodswing = models.IntegerField(choices=MOODSWING_CHOICES)
	created_at = models.DateTimeField(auto_now_add =True)

moods/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from .models import Mood

class MoodView(CreateView):
    model = Mood
    fields = ['moodswing', ]
    success_url = reverse_lazy('moods')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['moods'] = Mood.objects.order_by('-created_at')
        return context

moods/templates/base.html
{% load static %}<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Suhail Vs{% endblock %}</title>
    <link rel="icon" href="{% static 'favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block css %}
    {% endblock %}
  </head>
  <body>
    <div class="container my-4">
      <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
          <div class="card mb-3">
            <div class="card-body">
              {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                </div>
              {% endfor %}
              {% block content %}
              {% endblock %}
            </div>
          </div>
        </div>
      </div>
    </div>
    {% block js %}
    {% endblock %}
  </body>
</html>

moods/templates/moods/mood_form.html
{% extends 'base.html' %}

{% block content %}
  <h2>Enter your mood</h2>
  <form method="post">{% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-10">
  	  <select class="form-control" name="{{form.moodswing.name}}" onchange="onSubmit(this)">
  	  	{% for value, text in form.moodswing.field.choices %}
  			    <option value="{{ value }}">{{ text }}</option>
  			{% endfor %}
  	  </select>
      </div>
      <div class="form-group col-md-2">
        <input id="txtpassword" type="text" name="password" class="form-control">
      </div>
    </div>
	</form><hr>
  <table class="table table-striped table-bordered">
    <thead>
      <tr><th>Mood</th><th>Date</th></tr>
    </thead>
    <tbody>
      {% for mood in moods %}
      <tr>
      	<td>{{mood.get_moodswing_display}}</td>
      	<td>{{ mood.created_at|date:"ga D d M" }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

{% block js %}
<script type="text/javascript">
function onSubmit(selectObject) {
  let pass = document.getElementById("txtpassword").value;
  if (pass==1) {
    selectObject.form.submit()
  }
  
}
</script>
{% endblock %}